name: "DEPBADGE"
author: "Eugen Hildt"
description: Auto-generate Shields.io badges from your project manifest and embed them in README.md.

branding:
  icon: "tag"
  color: "purple"

runs:
  using: "node24"
  main: "dist/index.mjs"

outputs:
  badges-json:
    description: "Path to the `.depbadge` folder containing badge.json files and preview"
  badges-readme:
    description: "Path to the updated README.md"